### ISSUE TITLE
1.21.10 support

### ISSUE THREAD

**Issue by UniversalBank02** [TownyAdvanced/TownyFlight#97]
the current stable release doesn't work on 1.21.10. hope to see support soon! thanks

**Comment by UniversalBank02** [comment]
```
[22:23:11 ERROR]: Error occurred while enabling TownyFlight v1.13.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/palmergames/adventure/text/Component
        at TownyFlight-1.13.0 (2).jar/com.gmail.llmdlio.townyflight.TownyFlight.registerEvents(TownyFlight.java:126) ~[TownyFlight-1.13.0 (2).jar:?]
        at TownyFlight-1.13.0 (2).jar/com.gmail.llmdlio.townyflight.TownyFlight.onEnable(TownyFlight.java:63) ~[TownyFlight-1.13.0 (2).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.21.10-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.10.jar:1.21.10-73-b57d641]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.10.jar:1.21.10-73-b57d641]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.10-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.10.jar:1.21.10-73-b57d641]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[paper-1.21.10.jar:1.21.10-73-b57d641]
        at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:619) ~[paper-1.21.10.jar:1.21.10-73-b57d641]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:368) ~[paper-1.21.10.jar:1.21.10-73-b57d641]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1245) ~[paper-1.21.10.jar:1.21.10-73-b57d641]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:366) ~[paper-1.21.10.jar:1.21.10-73-b57d641]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.palmergames.adventure.text.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:208) ~[paper-api-1.21.10-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:175) ~[paper-api-1.21.10-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 13 more
[22:23:11 INFO]: [TownyFlight] Disabling TownyFlight v1.13.0
```
